### ISSUE TITLE
Deploy first version to hex.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-experiments/crypto#1]
Should probably be a 0.1.0 because I don't think we've found a stable API yet,
Was previously depending on a git version of stdlib but features now exist in stdlib 0.10.0

NOTE gleam_bitwise depends on an uncompatible version of stdlib currently, can either post a new gleam_bitwise version to hex otherwise will require stdlib to be specified in the deps.

**Comment by lpil** [comment]
Good idea, I'll do that now!

Rebar will override the bitwise stdlib version, and I think mix will too? Did you have a problem when you tried it?

**Comment by CrowdHailer** [comment]
mix you need to explicitly set `override` on your mix deps. but that's been working fine when I remember

**Comment by lpil** [comment]
It would be ideal if we didn't need to do that. I wonder if there's something like `~>` that I'm supposed to use with rebar.

**Comment by CrowdHailer** [comment]
Don't know about rebar.

Even with the `~>` in mix it doesn't take you over breaking changes. so If i set bitwise to `~> 0.10.0` that works for `0.10.x` but not `0.11.0`

**Comment by lpil** [comment]
Aye, I know. I'm wondering if there's something we can use in rebar to get that same flexible versioning, it sounds it it's an exact version when combined with mix from what you're saying

**Comment by CrowdHailer** [comment]
with mix it's variable in the last digit you define. 
`~> 0.10.0` = `0.10.0` `0.10.1` 
`~> 0.10` = `0.10.0` `0.10.1` `0.11.0`

**Comment by lpil** [comment]
Aye, as I've said I'm familiar with ~>

**Comment by CrowdHailer** [comment]
oh you mean "an exact version when [rebar] combined with mix"

**Comment by lpil** [comment]
Oops, yes, sorry!
