### ISSUE TITLE
Suggestion: rename Crypto module to Sha

### ISSUE THREAD

**Issue by sporto** [gleam-experiments/crypto#5]
I suppose that evantually this library will have other algorithms like BCrypt and Argon2 (more suitable for password hashing).

But putting these in the `Crypto` module will be confusing. So it would make sense to have modules like `Sha`, `Argon2`, ... instead.

Consider renaming the current `Crypto` module to `Sha` or `SecureHash`
Thanks

**Comment by lpil** [comment]
I think that would be confusing given only one of the 6 functions in that module is for hashing. We would need to move the other elsewhere?

I'm also not sure we could implement bcrypt and argon2 without C extensions, if so we'd be unlikely to have them in this package.
